### ISSUE TITLE
Does not seem to work in FF and Safari on a Mac

### ISSUE THREAD

**Issue by juanmendes** [silentmantra/benchmark#1]
I used benchmark on this [StackOverflow post](https://stackoverflow.com/questions/51185/are-javascript-strings-immutable-do-i-need-a-string-builder-in-javascript/4717855#) but it does not work on Firefox and Safari. The times are shown as undefined on both browsers for each test case.

<img width="673" alt="image" src="https://github.com/silentmantra/benchmark/assets/549331/a5a53a40-6bef-45ea-8c05-08197bf9bfbb">

**Comment by silentmantra** [comment]
fixing asap, thanks for reminding this known problem
i hope will be fixed tomorrow

**Comment by juanmendes** [comment]
Seems fixed. Added screenshots for FF and Safari on the [SO post](https://stackoverflow.com/a/4717855/227299) .

![image](https://github.com/silentmantra/benchmark/assets/549331/40ed9b15-34e1-4729-87d4-0c1fa4bb93dd)
